services:
#    formation.example:
#        class: FormationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     formation.display_block.hello:
         class: 'FormationBundle\DisplayBlock\Strategies\HelloStrategy'
         arguments:
            - '@request_stack'
            - '@open_orchestra_model.repository.content'
         tags:
            - { name: 'open_orchestra_display.display_block.strategy'}
