filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - 'app/*'
        - 'bin/*'
        - 'library/*'
    paths: {  }
tools:
    php_sim:
        enabled: true
    php_pdepend:
        enabled: true
    php_analyzer:
        enabled: true
    php_changetracking:
        enabled: true
application:
    type: none
