language: php

sudo: false

dist: precise

cache:
  directories:
    - ~/.composer/cache

matrix:
  include:
    - env: MONGOPHP=2.6.5.6
      php: 5.6
      addons:
        apt:
          packages:
            - libav-tools
            - mongodb-org-server
          sources:
            - mongodb-upstart
    - env: MONGOPHP=3.0.5.6
      php: 5.6
      addons:
        apt:
          packages:
            - libav-tools
            - mongodb-org-server
          sources:
            - mongodb-3.0-precise
    - env: MONGOPHP=2.6.7.0
      php: 7.0
      addons:
        apt:
          packages:
            - libav-tools
            - mongodb-org-server
          sources:
            - mongodb-upstart
    - env: MONGOPHP=3.0.7.0
      php: 7.0
      addons:
        apt:
          packages:
            - libav-tools
            - mongodb-org-server
          sources:
            - mongodb-3.0-precise

before_install:
  - printf "\n" |pecl install imagick
  - printf "\n" |pecl install mongodb
  - cp .travis.php_$(phpenv version-name).ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer install --prefer-dist

before_script:
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
  - php app/console orchestra:mongodb:fixtures:load --type=functional -e=test

script:
  - phpunit --testsuite=unit
  - phpunit --testsuite=functional
