imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: orchestra.yml }

framework:
    esi:             { enabled: true }
    translator:      { fallback: "%default_locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%default_locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       { path: /_fragment }
    http_method_override: true
    serializer:
        enabled: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
    get_set_method_normalizer:
       class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
       tags:
           - { name: serializer.normalizer }

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - OpenOrchestraFrontBundle
        - OpenOrchestraDisplayBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

doctrine_mongodb:
    connections:
        default:
            server: "%open_orchestra_cms.mongodb.server%"
            options: {}
    default_database: "%open_orchestra_cms.mongodb.database%"
    resolve_target_documents:
            OpenOrchestra\ModelInterface\Model\TranslatedValueInterface: OpenOrchestra\ModelBundle\Document\TranslatedValue
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://localhost
            logging: %kernel.debug%

open_orchestra_base:
    encryption_key: %encryption_key%

knp_gaufrette:
    adapters:
        media_storage:
            local:
                directory: %media.directory%
                create: true
    filesystems:
        media_storage:
            adapter: media_storage
            alias: media_storage_filesystem

open_orchestra_front:
    devices:
        web: ~
        tablet:
            parent: web
        phone:
            parent: web
        android:
            parent: phone

fos_http_cache:
    proxy_client:
        varnish:
            servers: "%fos_http_cache.proxy_client.varnish.servers%"
            base_url: "%fos_http_cache.proxy_client.varnish.base_url%"
        default: varnish

innocead_captcha:
    width: 150
    height: 30
    max_chars: 6
    min_chars: 5
    bg_transparent: false
    bg_red: 255
    bg_green: 255
    bg_blue: 255

open_orchestra_media:
    media_domain: %media_domain%
