open_orchestra_theme:
    themes:
        themePresentation:
            name: "Open Orchestra"
            stylesheets:
                - OpenOrchestraStyleBundle:demo:reset.css
                - OpenOrchestraStyleBundle:demo:style.css
                - OpenOrchestraStyleBundle:demo:layout.css
                - OpenOrchestraStyleBundle:demo:menu.css
                - OpenOrchestraStyleBundle:demo:footer.css
                - OpenOrchestraStyleBundle:demo:sidebar.css
                - OpenOrchestraStyleBundle:demo:blocks.css