open_orchestra_theme:
    themes:
        themePresentation:
            name: "Open Orchestra"
            stylesheets:
                - OpenOrchestraDemoBundle:demo:reset.css
                - OpenOrchestraDemoBundle:demo:style.css
                - OpenOrchestraDemoBundle:demo:layout.css
                - OpenOrchestraDemoBundle:demo:menu.css
                - OpenOrchestraDemoBundle:demo:footer.css
                - OpenOrchestraDemoBundle:demo:sidebar.css
                - OpenOrchestraDemoBundle:demo:contact_page.css
