open_orchestra_front:
    resource: '@OpenOrchestraFrontBundle/Controller'
    type: annotation

open_orchestra_front_preview:
    resource: '@OpenOrchestraFrontBundle/Resources/config/preview_routing.yml'

open_orchestra_media_get:
    path: /media/{key}
