parameters:
    open_orchestra_demo_bundle.display.footer.class: OpenOrchestra\DemoBundle\DisplayBlock\Strategies\DemoFooterStrategy
services:
    open_orchestra_display.display.footer:
        class: %open_orchestra_demo_bundle.display.footer.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @open_orchestra_base.manager.tag
        tags:
            - { name: open_orchestra_display.display_block.strategy }